DATABASE_URL = "postgresql://db_jht_q05l_user:wKpJM7Ydjue3L0r37Cb2DCOKzpC597bI@dpg-d8pn72jtqb8s738bl1d0-a.virginia-postgres.render.com/db_tracking"
SECRET_KEY = "clave_super_secreta"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

""""
---- LOCAL

DATABASE_URL = "postgresql://db_jht_q05l_user:wKpJM7Ydjue3L0r37Cb2DCOKzpC597bI@dpg-d8pn72jtqb8s738bl1d0-a.virginia-postgres.render.com/db_tracking"
SECRET_KEY = "clave_super_secreta"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

CREAS
ARCHIVO.ENV - RENDER
PRODUCCION - -
DATABASE_URL = DATABASE_URL_RENDER
SECRET_KEY = SECRET_KEY_RENDER
ALGORITHM = ALGORITHM_RENDER
ACCESS_TOKEN_EXPIRE_MINUTES = ACCESS_TOKEN_EXPIRE_MINUTES_RENDER

"""

